name: ecco
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - libffi=3.4.4
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - python=3.10.13
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - accelerate==0.26.1
      - aiohttp==3.9.3
      - aioprometheus==23.12.0
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.2.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.43.1
      - black==23.11.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.29.1
      - coloredlogs==15.0.1
      - comm==0.2.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.16.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepspeed==0.14.2
      - dill==0.3.7
      - diskcache==5.6.3
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastapi==0.109.0
      - fastchat==0.1.0
      - filelock==3.13.1
      - flash-attn==2.5.0
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gdown==5.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.4
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - idna==3.6
      - interegular==0.3.3
      - ipykernel==6.29.0
      - ipython==8.20.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.4.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - kiwisolver==1.4.5
      - lark==1.1.9
      - lightning-utilities==0.9.0
      - llvmlite==0.42.0
      - markupsafe==2.1.3
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numba==0.59.1
      - numpy==1.26.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.52
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.13.3
      - optimum==1.16.2
      - orjson==3.9.12
      - outlines==0.0.34
      - packaging==23.2
      - pandarallel==1.6.5
      - pandas==2.1.2
      - parso==0.8.3
      - pathspec==0.11.2
      - peft==0.3.0
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.0.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.2
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyaml==23.12.0
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pygments==2.17.2
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - quantile-python==1.1
      - ray==2.9.1
      - referencing==0.32.1
      - regex==2023.12.25
      - requests==2.31.0
      - rpds-py==0.17.1
      - safetensors==0.4.2
      - scikit-learn==1.5.0
      - scipy==1.13.0
      - sentencepiece==0.1.99
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - singularity-compose==0.1.18
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - spython==0.3.13
      - stack-data==0.6.3
      - starlette==0.35.1
      - sympy==1.12
      - threadpoolctl==3.5.0
      - tiktoken==0.6.0
      - tokenizers==0.15.1
      - tomli==2.0.1
      - torch==2.1.2
      - torchmetrics==1.2.0
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.1
      - transformers==4.39.3
      - triton==2.1.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - uvicorn==0.27.0
      - uvloop==0.19.0
      - vllm==0.4.0.post1
      - wandb==0.16.6
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - websockets==12.0
      - xformers==0.0.23.post1
      - xxhash==3.4.1
      - yarl==1.9.4
